---
pull_request_rules:
  - actions:
      merge:
        method: rebase
        rebase_fallback: null
        strict: true
    conditions:
      - label=ready-to-merge
      - '#approved-reviews-by>=1'
      - status-success=lint
      - status-success=docs
      - status-success=ci/jenkins/pr_cloud_crate-operator
      - status-success=docs/readthedocs.org:crate-operator
    name: default
