
pull_request_rules:
  - name: default
    conditions: []
    actions:
      queue:
queue_rules:
  - name: default
    queue_conditions:
      - label=ready-to-merge
      - '#approved-reviews-by>=1'
      - status-success=lint
      - status-success=docs
      - status-success=test
      - status-success=docs/readthedocs.org:crate-operator
    merge_conditions:
      - check-success=lint
      - check-success=docs
      - check-success=test
      - check-success=docs/readthedocs.org:crate-operator
    merge_method: merge
