# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: "3.8.4"
  hooks:
  - id: flake8
- repo: https://github.com/timothycrosley/isort
  rev: "5.6.4"
  hooks:
  - id: isort
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: "v0.770"
  hooks:
  - id: mypy
- repo: https://github.com/adrienverge/yamllint
  rev: "v1.25.0"
  hooks:
  - id: yamllint
    exclude: "^(\\.pre-commit-config\\.yaml|\\.github/workflows/.*|\\.github/dependabot\\.yml)$"
