---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: statefulset-reader
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-statefulset
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: statefulset-reader
subjects:
  - kind: ServiceAccount
    name: default
