# CrateDB Kubernetes Operator
# Copyright (C) 2020 Crate.IO GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crate-operator
  namespace: crate-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crate-operator
rules:
# Framework: posting the events about the handlers progress/errors
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
# Application: watching & handling for the custom resources
- apiGroups:
  - cloud.crate.io
  resources:
  - cratedbs
  verbs:
  - get
  - list
  - watch
  - patch
# Application: other resources it produces and manipulates
- apiGroups:
  - ""
  - apps
  - batch
  resources:
  - configmaps
  - cronjobs
  - deployments
  - namespaces
  - persistentvolumeclaims
  - persistentvolumes
  - pods
  - secrets
  - services
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crate-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crate-operator
subjects:
- kind: ServiceAccount
  name: crate-operator
  namespace: crate-operator
