#!/bin/sh

# DC Util Caddyfile Generator
# This script generates a Caddyfile for serving dc_util binaries with version API

set -e

# Configuration
OUTPUT_FILE=${1:-"/app/config/Caddyfile"}
BINARY_DIR=${2:-"/srv/binaries"}
PORT=${3:-"8080"}

echo "=== DC Util Caddyfile Generator ==="
echo "Output file: $OUTPUT_FILE"
echo "Binary directory: $BINARY_DIR"
echo "Port: $PORT"
echo "=================================="

# Ensure output directory exists
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Generate Caddyfile
cat > "$OUTPUT_FILE" << EOF
# DC Util Multi-Version Fileserver Configuration
# Generated by generate-caddyfile.sh

:$PORT {
    # Serve binary files from the binaries directory
    root * $BINARY_DIR
    file_server browse {
        hide .DS_Store
    }

    # API endpoint to list available versions
    @api path /api/versions
    respond @api \`[
EOF

# Add version list to API response
if [ -d "$BINARY_DIR" ]; then
    cd "$BINARY_DIR"
    VERSIONS=""
    for dir in */; do
        if [ -d "$dir" ] && [ "$dir" != "./" ]; then
            version=${dir%/}
            if [ -z "$VERSIONS" ]; then
                VERSIONS="\"$version\""
            else
                VERSIONS="$VERSIONS, \"$version\""
            fi
        fi
    done
    echo "$VERSIONS" >> "$OUTPUT_FILE"
fi

cat >> "$OUTPUT_FILE" << 'EOF'
]\` 200

    # Set JSON content type for API responses
    header @api Content-Type "application/json"

    # Security headers
    header {
        X-Content-Type-Options nosniff
        X-Frame-Options DENY
        X-XSS-Protection "1; mode=block"
    }

    # Logging
    log {
        output stdout
        format json
    }

    # Custom error pages
    handle_errors {
        respond "Error {http.error.status_code}: {http.error.status_text}"
    }
}
EOF

echo "✅ Caddyfile generated successfully"

# Validate the Caddyfile syntax (if caddy is available)
if command -v caddy >/dev/null 2>&1; then
    echo "🔍 Validating Caddyfile syntax..."
    if caddy validate --config "$OUTPUT_FILE" --adapter caddyfile; then
        echo "✅ Caddyfile syntax is valid"
    else
        echo "❌ Caddyfile syntax validation failed"
        exit 1
    fi
else
    echo "ℹ️ Caddy not available for syntax validation"
fi

echo "🎉 Caddyfile generation completed!"
