# Please note that this adds issues to a private project which is maintained by Crate.io.
# This allows us to triage and promptly come back to the creators.
name: Add new issues to the right project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.0.5 # Have to use a pretty old version due to it being a classic project.
        with:
          project-url: https://github.com/orgs/crate/projects/16
          github-token: ${{ secrets.JENKINS_USER_TOKEN }}
